# Site settings
title: My Space
email: angi.wang.afe@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  事在人为，天命难违
baseurl: "" # the subpath of your site, e.g. /blog/
url: http://angi.wang # the base hostname & protocol for your site
rss_url: /pages/feed.xml
author: Angi WANG

# Sidebar filter
# Choose 'tag' or 'category' as filter in sidebar.
filter: 'category'
recent_num: 20

# Social account
#twitter: masonsuyan
#weibo: suyan0830
github: AngiWANG
#instagram: suyan0830
#linkedin: suyan0830

# avatar and Favicon
avatar: /images/avatar.jpg 
favicon: /images/favicon.ico

# disqus config
# disqus:
#  shortname: suyan-zh

# google analytics config
ga:
  id: UA-54767140-1
  url: yansu.org

# Build settings
permalink: /:year/:month/:day/:title.html
markdown: kramdown
highlighter: rouge
mathjax: disabled
sass:
  style: compressed

# Jekyll Plugin
# https://help.github.com/articles/adding-jekyll-plugins-to-a-github-pages-site/
gems:
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-feed

